#include <rgb.h>

prog_uint16_t prog_segments[NUM_FIBERS][PROG_SIZE] PROGMEM =
  {
    {DONE_OPCODE}
  , {0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}

  , {0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {100, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {200, WAIT_OPCODE, 0, FOR_OPCODE,  0, 40, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}

  , {0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {100, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {200, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}

  , {100, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {200, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}

  , {0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {100, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {200, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}

  , {0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {100, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  , {200, WAIT_OPCODE, 0, FOR_OPCODE,  0, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, INCR_OPCODE,  2, WAIT_OPCODE, LOOP_OPCODE, DUTY_CYCLE_RESOLUTION, FOR_OPCODE, DUP_OPCODE, OUTPUT_OPCODE, DEC_OPCODE, 2, WAIT_OPCODE, LOOP_OPCODE, DROP_OPCODE, EVER_OPCODE, DONE_OPCODE}
  };

FiberConfig fiberConfigs[NUM_FIBERS] = 
  {
     {1, &prog_segments[0][0]}
  ,  {1, &prog_segments[1][0]}
  ,  {1, &prog_segments[2][0]}
  ,  {1, &prog_segments[3][0]}
  ,  {1, &prog_segments[4][0]}
  ,  {1, &prog_segments[5][0]}
  ,  {1, &prog_segments[6][0]}
  ,  {1, &prog_segments[7][0]}
  ,  {1, &prog_segments[8][0]}
  ,  {1, &prog_segments[9][0]}
  ,  {1, &prog_segments[10][0]}
  ,  {1, &prog_segments[11][0]}
  ,  {1, &prog_segments[12][0]}
  ,  {1, &prog_segments[13][0]}
  ,  {1, &prog_segments[14][0]}
  ,  {1, &prog_segments[15][0]}
  };

